adding zap scan

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -22,10 +22,25 @@ jobs:
       - run: docker build -t hub.klickstartonline.com/app .
       - run: docker push hub.klickstartonline.com/app
       - run: ssh-keyscan app.klickstartonline.com >> ~/.ssh/known_hosts
+
+      # run zap scan
+      - run:
+          name: ZAP baseline test of application
+          # Only fail on error code 1, which indicates at least one FAIL was found.
+          # error codes 2 & 3 indicate WARN or other, and should not break the run
+          command: |
+            (
+            docker pull owasp/zap2docker-weekly && \
+            docker run -t owasp/zap2docker-weekly zap-baseline.py \
+                -t http://127.0.0.1:80/ || \
+            if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
+            )
+
       - run:
           name: Deploy Over SSH
           command: |
             ssh ubuntu@app.klickstartonline.com  "/home/ubuntu/VulnNodeApp/update.sh"
+
 workflows:
   version: 2
   # build
@@ -41,14 +56,6 @@ workflows:
       - owasp/commandline_owasp_dependency_check:
           arguments: >-
             --scan ./ --failOnCVSS 7
-      - zap-scan:
-          command: |
-            (
-            docker pull owasp/zap2docker-weekly && \
-            docker run -t owasp/zap2docker-weekly zap-baseline.py \
-                -t http://127.0.0.1:8080/ || \
-            if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
-            )
       - deploy:
           requires: 
             - owasp/commandline_owasp_dependency_check
