added zap scan

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -26,6 +26,19 @@ jobs:
           name: Deploy Over SSH
           command: |
             ssh ubuntu@app.klickstartonline.com  "/home/ubuntu/VulnNodeApp/update.sh"
+      
+      # run zap scan
+      - run:
+          name: ZAP baseline test of application
+          # Only fail on error code 1, which indicates at least one FAIL was found.
+          command: |
+            (
+            docker pull owasp/zap2docker-weekly && \
+            docker run -t owasp/zap2docker-weekly zap-baseline.py \
+                -t http://127.0.0.2:80/ || \
+            if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
+            )
+            
 workflows:
   version: 2
   # build
@@ -44,14 +57,3 @@ workflows:
       - deploy:
           requires: 
             - owasp/commandline_owasp_dependency_check
-      - zap-baseline-scan:
-        - run:
-            name: ZAP baseline test of application
-            # Only fail on error code 1, which indicates at least one FAIL was found.
-            command: |
-              (
-              docker pull owasp/zap2docker-weekly && \
-              docker run -t owasp/zap2docker-weekly zap-baseline.py \
-                  -t http://127.0.0.2:80/ || \
-              if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
-              )
